src/components/NavBar/index.jsx, src/components/NavBar/style.js, src/index.css
- Specify : full layout size 640px
- Modify and design : the navigation bar
=> #4 nav bar

dummyServer/db.json, dummyServer/index.js
기존 PR 을 다시 열 수 없어서 다시 올립니다.
[API 명세](https://www.notion.so/44b2aa312d454b7987d10e972ad50675?v=8290f737622e4d1eb731726ae0443af8)
이메일 인증과 카트/관심상품도 상품데이터를 직접 가져오도록 수정하였습니다
=> #6 conf: Update dummy server

src/App.tsx, src/api/searchApi.ts, src/components/Button/index.jsx, src/components/Input/index.jsx, src/components/ProductOrderBar/hook.ts, src/components/ProductOrderBar/index.tsx, src/components/ProductOrderBar/style.ts, src/components/ProductSearchBar/SearchInput/index.tsx, src/components/ProductSearchBar/SearchInput/style.ts, src/components/ProductSearchBar/hook.ts, src/components/ProductSearchBar/index.tsx, src/components/ProductSearchBar/style.ts, src/components/Select/index.tsx, src/constants/orderBar.ts, src/constants/searchBar.ts, src/hooks/useDebounce.ts, src/modules/index.tsx, src/pages/pagesPath.js, src/types/product.ts, src/utils/convertRTKQueryErrorToError.ts, src/utils/mapObject.ts
스타일과 필요한 부분을 제외하면 일단 적용을 위해 올립니다.
=> feat: Create Search components

.gitignore, dummyServer/db.json, dummyServer/index.js, yarn.lock
- /fav, /cart request body 에 기존에 단일로 보냈던 것을 리스트 형태로 업데이트
- 테스트 계정 추가
email: test@test.com
password: test@test.com
=> conf: Update dummyServer

src/App.tsx, src/pages/pagesPath.js
- 1차 Route 정리
- pagesFullPath 로 url 사용 편하게 이용하세요!
=> feat: Update Route and pagesPath.js

src/components/CartListTemplate/CartListHeader/style.ts
=> #10 fix: Update missing Components

src/modules/favoriteSlice.js, src/modules/index.tsx, src/pages/FavoriteProductsPage/index.jsx
=> #13 feat: Create Favorite Slice

src/components/ProductCard/data.js, src/components/ProductCard/index.jsx, src/components/ProductCard/style.js, src/components/ProductDetailModal/index.jsx, src/index.css, src/pages/AllProductsPage/index.jsx, src/styles/globalStyle.js
#feat/Component
- ProductModal sample layout Display
- merge component folder (ProductCard, ProductDetailModal)
- index.css refactor and Global Style Add.
=> #30 feat: ProductModal sample layout Display

src/components/ProductCard/index.jsx
- Click to synchronize product card components and modal components
=> 31 feat:Click to synchronize ProductCardComponents and ModalComponent

src/App.tsx, src/pages/AllProductsPage/index.jsx, src/pages/HomePage/index.jsx, src/pages/RequireAuth/index.tsx
- accessToken 없을 때 '/signin' 로 이동
- '/' 접속 시 accessToken 이 있으면 '/products/personal' 없으면 '/signin' 으로 이동
=> #18 feat: Add Guard and Update Route

src/components/CartListTemplate/index.tsx, src/components/PageHeading/index.tsx, src/pages/CartPage/index.tsx
=> #10 feat: Add PageHeading

src/App.tsx
=> #18 fix: Apply nest Products Page

src/components/ProductCard/index.jsx, src/components/ProductCard/style.js, src/pages/AllProductsPage/index.jsx
=> #46 product card chkbox

dummyServer/db.json, src/components/FavoriteCard/FavoriteCard.jsx, src/components/FavoriteCard/style.js, src/components/ProductCard/index.jsx, src/components/common/FavoriteButton/FavoriteButton.jsx, src/modules/favoriteSlice.js, src/pages/FavoriteProductsPage/index.jsx
=> #13 Favorite

src/components/CartListTemplate/CartListHeader/style.ts, src/components/PageHeading/index.tsx, src/components/ProductOrderBar/index.tsx, src/components/ProductOrderBar/style.ts, src/components/ProductSearchBar/SearchInput/index.tsx, src/components/ProductSearchBar/SearchInput/style.ts, src/components/ProductSearchBar/index.tsx, src/components/ProductSearchBar/style.ts, src/components/common/Button/style.js, src/pages/AllProductsPage/index.jsx, src/pages/CartPage/index.tsx, src/pages/CartPage/style.ts, src/styles/theme.js
- Add PageHeading
- Button styling
- Add theme.colors.primary
=> #10 design: Apply LITTLE Cart

dummyServer/db.json, dummyServer/index.js, src/types/product.ts
- 더비 서버 url 이랑 Request, Response 형식 최대한 맞춤
=> #2 conf: Matching dummy-server to real-server

src/assets/icons/check_FILL0_wght700_GRAD0_opsz24.svg, src/components/ProductOrderBar/hook.ts, src/components/common/Input/InputRadio/index.tsx, src/pages/AllProductsPage/index.jsx, src/styles/styled.d.ts
- 커밋이 꼬여서................................. 빠진 부분 올립니다.
=> #2 hotfix: Missing rename propertys

package.json, yarn.lock
- esline@^8.23.0
- typescript@^4.8.2
=> conf: Bump package

src/api/baseQuery.ts, src/api/cartApi.ts, src/api/searchApi.ts, src/components/CartListTemplate/hook.tsx, src/components/PageDescription/index.tsx, src/pages/CartPage/index.tsx
- PageDescription 추가
사용법은 CartPage 가셔서 참고하세요
- .env 적용
=> #10 feat: Add PageDescription

dummyServer/db.json, src/api/productApi.js, src/components/ProductCardList/index.jsx, src/modules/index.tsx, src/styles/globalStyle.js
##feat/Component
- ProductApi Connected
- globalstyle fix
=> #58 product api

src/components/ProductSearchBar/index.tsx, src/hooks/useGoSignUpHasAuthError.ts, src/pages/AllProductsPage/index.jsx, src/pages/RequireAuth/index.tsx, src/utils/isAuthError.ts
- isAuthError 추가
- 각 페이지에서 처리해주는 것이 안전함
- 상위에서 auth 에러나면 해주긴 함
=>  #18 feat: Add isAuthError 

src/components/CartListTemplate/CartList/index.tsx, src/components/NavBar/style.js, src/components/ProductCardList/index.jsx, src/components/ProductCardList/style.js, src/pages/AllProductsPage/index.jsx, src/pages/FavoriteProductsPage/index.jsx, src/styles/globalStyle.js, src/styles/theme.js
- ProductCard Api Connected
- change body width
=> #59 feat:ProductCard Api Connected and Change body width

dummyServer/db.json, src/components/ProductCardList/index.jsx, src/components/ProductCardList/style.js, src/styles/globalStyle.js, src/styles/theme.js
##design/Component
- Apply style to ProductCardList Component (Card and Modal)
- Modified globalStyle font-size format (px to rem)
=> #71 design:Apply style to ProductCardList Component

src/api/favoriteApi.js, src/components/FavoriteCard/index.jsx, src/components/FavoriteCard/style.js, src/components/common/FavoriteButton/FavoriteButton.jsx, src/pages/FavoriteProductsPage/index.jsx
=> #13 Add Fav. Card

src/components/NavBar/style.js, src/components/ProductCardList/index.jsx
- NavBar css
- ProductCardList prettier formating
=> #72 design:NavBar z-index and ProductCardList prettier formating

src/components/NavBar/index.jsx, src/components/ProductCardList/index.jsx, src/components/ProductCardList/style.js
-Apply style to NavBar and ProductCardList Modal close button
=> #71 design:Apply style to NavBar and ProductCardList Modal close button

package.json, src/api/productCustom.ts, src/components/ProductCardList/index.jsx, src/modules/index.tsx, src/pages/PersonalProductsPage/index.jsx, src/pages/PersonalProductsPage/index.tsx
=> #98 feat: Add PersonalProductPage

src/components/ProductCardList/index.jsx, src/components/ProductCardList/style.js
-apply to Button design and naming from Common directory
=> #71 design:apply to Button design

src/styles/globalStyle.js
-apply mediaquery css to globalStyle (using viewport-width)
=> #108 design:apply mediaquery css to globalStyle

src/components/common/FavoriteButton/FavoriteButton.jsx, src/modules/favoriteSlice.js, src/pages/FavoriteProductsPage/index.jsx
=> #13 Fav. Product Connect API done

src/components/ProductCardList/index.jsx, src/components/ProductCardList/style.js
design/Components
-ProductCardList Add icons
=> #71 design:ProductCardList Add icons
